### ISSUE TITLE
Feature request - add support for Prometheus service monitor

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/bundle-cert-manager#5]
When deploying this application using helm, we can set the following options:
```
prometheus:
  enabled: true
servicemonitor:
  enabled: true
```
Our use case requires these options for the charmed deployment.

See https://pastebin.ubuntu.com/p/4F6gXfBQYY/ for an example of what adding this change in helm does to modify the yaml definitions (includes another change to PSP as well).

**Comment by knkski** [comment]
Would it be sufficient to add support for a relation to this charm?

https://jaas.ai/u/charmcraft/prometheus

**Comment by Vultaire** [comment]
If the end result is equivalent to setting the two above-mentioned helm options, I think that may work for now.

Also, while I haven't done anything with this personally, [docs](https://cert-manager.io/docs/usage/prometheus-metrics/) seem to indicate the syntax of the helm config spec'd above should be:

```
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
```

That might be obvious to others, but wanted to call that out just in case.
